#!/usr/bin/env node

const oclif = require('@oclif/core');

if (process.argv[2] === 'dev-mode') {
    process.argv.splice(2, 1);

    const path = require('path');

    // In dev mode -> use ts-node and dev plugins
    process.env.NODE_ENV = 'development';

    // In dev mode, always show stack traces
    oclif.settings.debug = true;

    // Start the CLI
    oclif.run().then(oclif.flush).catch(oclif.Errors.handle);
} else {
    oclif.run().then(require('@oclif/core/flush')).catch(require('@oclif/core/handle'));
}
